name:                lambda-learner
version:             0.1.0.0
github:              "esennesh/lambda-learner"
license:             BSD3
author:              "Eli Sennesh"
maintainer:          "esennesh@ccis.neu.edu"
copyright:           "Eli Sennesh 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            machine-learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/esennesh/lambda-learner#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- monad-bayes
- transformers

library:
  source-dirs: src
  ghc-options:
    - -XLambdaCase
    - -XGADTs

executables:
  lambda-learner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XLambdaCase
    - -XGADTs
    dependencies:
    - lambda-learner

tests:
  lambda-learner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-learner
